Use ${NAME} variable for utility name.

diff --git a/twilog.in b/twilog.in
--- a/twilog.in
+++ b/twilog.in
@@ -1,13 +1,14 @@
 #!/bin/bash
 
 # Constants
+NAME="twilog"
 BASE_URL='https://api.twilio.com/'
 NOTIFICATIONS_PATH='/2010-04-01/Accounts/${ACCOUNT_SID}/Notifications?MessageDate\>=${START_DATE}\&PageSize=${PAGESIZE}'
 FACILITY_REGEX="^(auth|authpriv|cron|daemon|ftp|kern|lpr|mail|news|security|user|uucp|local[0-7])$"
 DEFAULT_FACILITY="user"
-DEFAULT_TAG="twilog"
+DEFAULT_TAG="${NAME}"
 INITIAL_START_DATE="2000-01-01"
-DEFAULT_STATEFILE='/var/lib/twilog/state.${ACCOUNT_SID}'
+DEFAULT_STATEFILE='/var/lib/${NAME}/state.${ACCOUNT_SID}'
 DEFAULT_CREDSFILE='@defaultconf@'
 PAGESIZE="1000"
 XMLSTARLET="@XMLSTARLET@"
@@ -21,7 +22,7 @@ DATE_PARSING_STYLE="@DATE_PARSING_STYLE@"
 # Usage message
 usage()
 {
-    echo "Usage: twilog [-d] [-i] [-m] [-c config] [-f facility] [-t tag] [-s statefile]" 1>&2
+    echo "Usage: ${NAME} [-d] [-i] [-m] [-c config] [-f facility] [-t tag] [-s statefile]" 1>&2
     echo "Options:" 1>&2
     echo "    -c    Specify credentials file (default \"${DEFAULT_CREDSFILE}\")" 1>&2
     echo "    -d    Debug mode: log to stdout instead of syslog" 1>&2
@@ -56,7 +57,7 @@ parse_date()
             "${DATE}" -j -f '%a, %d %b %Y %T %z' "${1}" "+${2}"
             ;;
         *)
-            echo "twilog: unknown date parsing style: ${DATE_PARSING_STYLE}" 1>&2
+            echo "${NAME}: unknown date parsing style: ${DATE_PARSING_STYLE}" 1>&2
             exit 1
             ;;
     esac
@@ -138,36 +139,36 @@ esac
 
 # See if credentials file is readable
 if ! test -r "${CREDSFILE}"; then
-    echo "twilog: can't read ${CREDSFILE}" 1>&2
+    echo "${NAME}: can't read ${CREDSFILE}" 1>&2
     exit 1
 fi
 
 # Parse credentials file
 . "${CREDSFILE}"
 if [ -z "${ACCOUNT_SID}" ]; then
-    echo "twilog: ACCOUNT_SID missing in ${CREDSFILE}" 1>&2
+    echo "${NAME}: ACCOUNT_SID missing in ${CREDSFILE}" 1>&2
     exit 1
 fi
 if [ -z "${AUTH_TOKEN}" ]; then
-    echo "twilog: AUTH_TOKEN missing in ${CREDSFILE}" 1>&2
+    echo "${NAME}: AUTH_TOKEN missing in ${CREDSFILE}" 1>&2
     exit 1
 fi
 
 # Create temporary files for response
-RESPONSE_FILE=`mktemp -q /tmp/twilog.XXXXXX`
+RESPONSE_FILE=`mktemp -q /tmp/${NAME}.XXXXXX`
 if [ $? -ne 0 ]; then
-    echo "twilog: can't create temporary file" 1>&2
+    echo "${NAME}: can't create temporary file" 1>&2
     exit 1
 fi
 trap "rm -f ${RESPONSE_FILE}" 0 2 3 5 10 13 15
 
 # Sanity check stuff
 if ! [[ "${ACCOUNT_SID}" =~ ^AC[0-9a-f]{32}$ ]]; then
-    echo "twilog: invalid account SID \`${ACCOUNT_SID}'" 1>&2
+    echo "${NAME}: invalid account SID \`${ACCOUNT_SID}'" 1>&2
     exit 1
 fi
 if ! [[ "${AUTH_TOKEN}" =~ ^[0-9a-f]{32}$ ]]; then
-    echo "twilog: invalid authentication token" 1>&2
+    echo "${NAME}: invalid authentication token" 1>&2
     exit 1
 fi
 
@@ -198,7 +199,7 @@ fi
 # Check result
 CURL_RESULT="$?"
 if [ "${CURL_RESULT}" -ne 0 ]; then
-    echo "twilog: error sending request (curl returned ${CURL_RESULT})" 1>&2
+    echo "${NAME}: error sending request (curl returned ${CURL_RESULT})" 1>&2
     exit 1
 fi
 
@@ -206,14 +207,14 @@ fi
 ERROR_CODE=`"${XMLSTARLET}" sel -T -t -m /TwilioResponse/RestException -v Code -n ${RESPONSE_FILE} 2>/dev/null`
 ERROR_MESSAGE=`"${XMLSTARLET}" sel -T -t -m /TwilioResponse/RestException -v Message -n ${RESPONSE_FILE} 2>/dev/null`
 if [ -n "${ERROR_CODE}" -o -n "${ERROR_MESSAGE}" ]; then
-    echo "twilog: Twilio REST error #${ERROR_CODE}: ${ERROR_MESSAGE}" 1>&2
+    echo "${NAME}: Twilio REST error #${ERROR_CODE}: ${ERROR_MESSAGE}" 1>&2
     exit 1
 fi
 
 # Extract SID of the most recent message (if any)
 NEW_LAST_SID=`"${XMLSTARLET}" sel -T -t -m '/TwilioResponse/Notifications/Notification[1]' -v Sid -n ${RESPONSE_FILE} 2>&1`
 if ! [[ "${NEW_LAST_SID}" =~ ^(NO[0-9a-f]{32})?$ ]]; then
-    echo "twilog: error parsing result: ${NEW_LAST_SID}" 1>&2
+    echo "${NAME}: error parsing result: ${NEW_LAST_SID}" 1>&2
     exit 1
 fi
 
@@ -287,7 +288,7 @@ fi
 # Update state file
 printf 'START_DATE='\''%s'\''\nLAST_SID='\''%s'\''\n' "${NEW_START_DATE}" "${NEW_LAST_SID}" > "${STATEFILE}"
 if [ $? -ne 0 ]; then
-    echo "twilog: error updating ${STATEFILE}" 1>&2
+    echo "${NAME}: error updating ${STATEFILE}" 1>&2
     exit 1
 fi
 
diff --git a/twimsg.in b/twimsg.in
--- a/twimsg.in
+++ b/twimsg.in
@@ -4,6 +4,7 @@
 set -e
 
 # Constants
+NAME="twimsg"
 DEFAULT_CONFIG_FILE='@defaultconf@'
 DEFAULT_TRUNCATE_LIMIT='3200'
 BASE_URL='https://api.twilio.com/'
@@ -19,7 +20,7 @@ SMSLEN="@bindir@/smslen"
 # Usage message
 usage()
 {
-    echo "Usage: twimsg [options] dest-number" 1>&2
+    echo "Usage: ${NAME} [options] dest-number" 1>&2
     echo "Options:" 1>&2
     echo "    -C curlflag       Pass curlflag to curl(1)" 1>&2
     echo "    -c file           Specify config file (default \"${DEFAULT_CONFIG_FILE}\")" 1>&2
@@ -85,7 +86,7 @@ while [ ${#} -gt 0 ]; do
             shift
             IMAGE_URL="${1}"
             if ! [[ "${IMAGE_URL}" =~ ^https?://[^[:space:]]+$ ]]; then
-                echo "twimsg: invalid image URL \`${IMAGE_URL}'" 1>&2
+                echo "${NAME}: invalid image URL \`${IMAGE_URL}'" 1>&2
                 exit 1
             fi
             shift
@@ -145,7 +146,7 @@ esac
 # Ensure config file is readable; if not, then what we need must be provided on the command line
 if ! test -r "${CONFIG_FILE}"; then
     if test -z "${OVERRIDE_FROM_NUMBER}" -o -z "${OVERRIDE_ACCOUNT_SID}" -o -z "${OVERRIDE_AUTH_TOKEN}"; then
-        echo "twimsg: can't read ${CONFIG_FILE}" 1>&2
+        echo "${NAME}: can't read ${CONFIG_FILE}" 1>&2
         exit 1
     fi
 else
@@ -170,19 +171,19 @@ TO_NUMBER=`normalize "${TO_NUMBER}"`
 
 # Sanity check stuff
 if ! [[ "${FROM_NUMBER}" =~ ^(\+1[2-9][0-9]{2}[2-9][0-9]{2}[0-9]{4}|[0-9]{5,6})$ ]]; then
-    echo "twimsg: invalid source phone number \`${FROM_NUMBER}'" 1>&2
+    echo "${NAME}: invalid source phone number \`${FROM_NUMBER}'" 1>&2
     exit 1
 fi
 if ! [[ "${TO_NUMBER}" =~ ^(\+1[2-9][0-9]{2}[2-9][0-9]{2}[0-9]{4}|[0-9]{5,6})$ ]]; then
-    echo "twimsg: invalid destination phone number \`${TO_NUMBER}'" 1>&2
+    echo "${NAME}: invalid destination phone number \`${TO_NUMBER}'" 1>&2
     exit 1
 fi
 if ! [[ "${ACCOUNT_SID}" =~ ^AC[0-9a-f]{32}$ ]]; then
-    echo "twimsg: invalid account SID \`${ACCOUNT_SID}'" 1>&2
+    echo "${NAME}: invalid account SID \`${ACCOUNT_SID}'" 1>&2
     exit 1
 fi
 if ! [[ "${AUTH_TOKEN}" =~ ^[0-9a-f]{32}$ ]]; then
-    echo "twimsg: invalid authentication token" 1>&2
+    echo "${NAME}: invalid authentication token" 1>&2
     exit 1
 fi
 
@@ -190,21 +191,21 @@ fi
 URL="`echo ${BASE_URL} | sed 's|/$||g'`""`eval echo ${ACCOUNTS_PATH}`"
 
 # Create temporary files for message response and error
-RESPONSE_FILE=`mktemp -q /tmp/twimsg.XXXXXX`
+RESPONSE_FILE=`mktemp -q /tmp/${NAME}.XXXXXX`
 if [ $? -ne 0 ]; then
-    echo "twimsg: can't create temporary file" 1>&2
+    echo "${NAME}: can't create temporary file" 1>&2
     exit 1
 fi
-OUTPUT_FILE=`mktemp -q /tmp/twimsg.XXXXXX`
+OUTPUT_FILE=`mktemp -q /tmp/${NAME}.XXXXXX`
 if [ $? -ne 0 ]; then
     rm -f ${RESPONSE_FILE}
-    echo "twimsg: can't create temporary file" 1>&2
+    echo "${NAME}: can't create temporary file" 1>&2
     exit 1
 fi
 trap "rm -f ${RESPONSE_FILE} ${OUTPUT_FILE}" 0 2 3 5 10 13 15
 
 # Truncate input and post to Twilio
-[ "${VERBOSE}" != 'true' ] || echo "twimsg: posting data to ${URL}" 1>&2
+[ "${VERBOSE}" != 'true' ] || echo "${NAME}: posting data to ${URL}" 1>&2
 cat "${INPUT_FILE}" \
   | "${ICONV}" -c -s -f "${ENCODING}" -t "${TWILIO_ENCODING}" \
   | "${SMSLEN}" -i "${TWILIO_ENCODING}" -t "${TRUNCATE_LIMIT}" \
@@ -220,11 +221,11 @@ cat "${INPUT_FILE}" \
 # Check result
 CURL_RESULT="$?"
 if [ "${CURL_RESULT}" -ne 0 ]; then
-    echo "twimsg: error sending request (curl returned ${CURL_RESULT})" 1>&2
+    echo "${NAME}: error sending request (curl returned ${CURL_RESULT})" 1>&2
     exit 1
 fi
 if [ "${VERBOSE}" = 'true' ]; then
-    echo "twimsg: received response:" 1>&2
+    echo "${NAME}: received response:" 1>&2
     cat "${RESPONSE_FILE}" 1>&2
     echo 1>&2
 fi
@@ -232,19 +233,19 @@ fi
 # Apply XSLT to returned XML to get error message
 "${XSLTPROC}" "${RESULT_XSL}" "${RESPONSE_FILE}" > "${OUTPUT_FILE}" 2>&1
 if [ $? -ne 0 ]; then
-    echo -n "twimsg: error parsing result:" 1>&2
+    echo -n "${NAME}: error parsing result:" 1>&2
     cat "${OUTPUT_FILE}" 1>&2
     exit 1
 fi
 if [ "${VERBOSE}" = 'true' ]; then
-    echo "twimsg: successfully parsed response:" 1>&2
+    echo "${NAME}: successfully parsed response:" 1>&2
     cat "${OUTPUT_FILE}" 1>&2
 fi
 
 # Get SMS ID or error response from output file
 SMS_ID=`cat "${OUTPUT_FILE}"`
 if ! [[ "${SMS_ID}" =~ ^SM[0-9a-f]{32}$ ]]; then
-    echo -n "twimsg: " 1>&2
+    echo -n "${NAME}: " 1>&2
     cat "${OUTPUT_FILE}" 1>&2
     exit 1
 fi
diff --git a/twiping.in b/twiping.in
--- a/twiping.in
+++ b/twiping.in
@@ -4,6 +4,7 @@
 set -e
 
 # Constants
+NAME="twiping"
 DEFAULT_CONFIG_FILE='@defaultconf@'
 BASE_URL='https://api.twilio.com/'
 ACCOUNTS_PATH='/2010-04-01/Accounts/${ACCOUNT_SID}/Messages'
@@ -27,7 +28,7 @@ DATE_PARSING_STYLE="@DATE_PARSING_STYLE@"
 # Usage message
 usage()
 {
-    echo "Usage: twiping [options] dest-number" 1>&2
+    echo "Usage: ${NAME} [options] dest-number" 1>&2
     echo "Options:" 1>&2
     echo "    -C curlflag       Pass curlflag to curl(1)" 1>&2
     echo "    -c file           Specify config file (default \"${DEFAULT_CONFIG_FILE}\")" 1>&2
@@ -155,7 +156,7 @@ esac
 # Ensure config file is readable; if not, then what we need must be provided on the command line
 if ! test -r "${CONFIG_FILE}"; then
     if test -z "${OVERRIDE_FROM_NUMBER}" -o -z "${OVERRIDE_ACCOUNT_SID}" -o -z "${OVERRIDE_AUTH_TOKEN}"; then
-        echo "twiping: can't read ${CONFIG_FILE}" 1>&2
+        echo "${NAME}: can't read ${CONFIG_FILE}" 1>&2
         exit 1
     fi
 else
@@ -183,19 +184,19 @@ TO_NUMBER=`normalize "${TO_NUMBER}"`
 
 # Sanity check stuff
 if ! [[ "${FROM_NUMBER}" =~ ^(\+1[2-9][0-9]{2}[2-9][0-9]{2}[0-9]{4}|[0-9]{5,6})$ ]]; then
-    echo "twiping: invalid source phone number \`${FROM_NUMBER}'" 1>&2
+    echo "${NAME}: invalid source phone number \`${FROM_NUMBER}'" 1>&2
     exit 1
 fi
 if ! [[ "${TO_NUMBER}" =~ ^(\+1[2-9][0-9]{2}[2-9][0-9]{2}[0-9]{4}|[0-9]{5,6})$ ]]; then
-    echo "twiping: invalid destination phone number \`${TO_NUMBER}'" 1>&2
+    echo "${NAME}: invalid destination phone number \`${TO_NUMBER}'" 1>&2
     exit 1
 fi
 if ! [[ "${ACCOUNT_SID}" =~ ^AC[0-9a-f]{32}$ ]]; then
-    echo "twiping: invalid account SID \`${ACCOUNT_SID}'" 1>&2
+    echo "${NAME}: invalid account SID \`${ACCOUNT_SID}'" 1>&2
     exit 1
 fi
 if ! [[ "${AUTH_TOKEN}" =~ ^[0-9a-f]{32}$ ]]; then
-    echo "twiping: invalid authentication token" 1>&2
+    echo "${NAME}: invalid authentication token" 1>&2
     exit 1
 fi
 
@@ -203,15 +204,15 @@ fi
 URL="`echo ${BASE_URL} | sed 's|/$||g'`""`eval echo ${ACCOUNTS_PATH}`"
 
 # Create temporary files for message response and error
-RESPONSE_FILE=`mktemp -q /tmp/twiping.XXXXXX`
+RESPONSE_FILE=`mktemp -q /tmp/${NAME}.XXXXXX`
 if [ $? -ne 0 ]; then
-    echo "twiping: can't create temporary file" 1>&2
+    echo "${NAME}: can't create temporary file" 1>&2
     exit 1
 fi
-ERROR_FILE=`mktemp -q /tmp/twiping.XXXXXX`
+ERROR_FILE=`mktemp -q /tmp/${NAME}.XXXXXX`
 if [ $? -ne 0 ]; then
     rm -f ${RESPONSE_FILE}
-    echo "twiping: can't create temporary file" 1>&2
+    echo "${NAME}: can't create temporary file" 1>&2
     exit 1
 fi
 trap "rm -f ${RESPONSE_FILE} ${ERROR_FILE}" 0 2 3 5 10 13 15
@@ -237,21 +238,21 @@ fi
 # Check result
 CURL_RESULT="$?"
 if [ "${CURL_RESULT}" -ne 0 ]; then
-    echo "twiping: error sending request (curl returned ${CURL_RESULT})" 1>&2
+    echo "${NAME}: error sending request (curl returned ${CURL_RESULT})" 1>&2
     exit 1
 fi
 
 # Apply XSLT to returned XML to get error message
 "${XSLTPROC}" "${RESULT_XSL}" "${RESPONSE_FILE}" > "${ERROR_FILE}" 2>&1
 if [ $? -ne 0 ]; then
-    echo -n "twiping: error parsing result:" 1>&2
+    echo -n "${NAME}: error parsing result:" 1>&2
     cat "${ERROR_FILE}" 1>&2
     exit 1
 fi
 
 # Was there an error returned?
 if [ -s "${ERROR_FILE}" ]; then
-    echo -n "twiping: " 1>&2
+    echo -n "${NAME}: " 1>&2
     cat "${ERROR_FILE}" 1>&2
     exit 1
 fi
@@ -267,7 +268,7 @@ while true; do
     CURRENT_TIME=`"${DATE}" -u +%s`
     ELAPSED_TIME=`"${EXPR}" "${CURRENT_TIME}" - "${START_TIME}" || true`
     if [ "${ELAPSED_TIME}" -ge "${MAX_WAIT_TIME}" ]; then
-        echo "twiping: no response after ${ELAPSED_TIME} seconds" 1>&2
+        echo "${NAME}: no response after ${ELAPSED_TIME} seconds" 1>&2
         exit 2
     fi
 
@@ -282,7 +283,7 @@ while true; do
     # Check result
     CURL_RESULT="$?"
     if [ "${CURL_RESULT}" -ne 0 ]; then
-        echo "twiping: error retrieving messages (curl returned ${CURL_RESULT})" 1>&2
+        echo "${NAME}: error retrieving messages (curl returned ${CURL_RESULT})" 1>&2
         exit 1
     fi
 
@@ -293,7 +294,7 @@ while true; do
     # Apply XSLT to returned XML to extract incoming messages
     "${XSLTPROC}" "${TWIPING_XSL}" "${RESPONSE_FILE}" > "${ERROR_FILE}" 2>&1
     if [ $? -ne 0 ]; then
-        echo -n "twiping: error parsing messages: " 1>&2
+        echo -n "${NAME}: error parsing messages: " 1>&2
         cat "${ERROR_FILE}" 1>&2
         exit 1
     fi
@@ -302,7 +303,7 @@ while true; do
     while IFS=/ read _SID _FROM _TO _DATE _BODY; do
         RESPONSE_TIME=`parse_date "${_DATE}" '%s'`
         if [ "${RESPONSE_TIME}" -ge "${START_TIME}" ]; then
-            echo "twiping: response from ${_FROM} after ${ELAPSED_TIME} seconds: ${_BODY}"
+            echo "${NAME}: response from ${_FROM} after ${ELAPSED_TIME} seconds: ${_BODY}"
             exit 0
         fi
     done < <("${GREP}" -E "${REPLY_PATTERN}" "${ERROR_FILE}")
