Allow programs to run without requiring a config file.

diff --git a/twiping.in b/twiping.in
--- a/twiping.in
+++ b/twiping.in
@@ -124,14 +124,16 @@ case "${#}" in
         ;;
 esac
 
-# See if config file is readable
+# Ensure config file is readable; if not, then what we need must be provided on the command line
 if ! test -r "${CONFIG_FILE}"; then
-    echo "twiping: can't read ${CONFIG_FILE}" 1>&2
-    exit 1
+    if test -z "${OVERRIDE_FROM_NUMBER}" -o -z "${OVERRIDE_ACCOUNT_SID}" -o -z "${OVERRIDE_AUTH_TOKEN}"; then
+        echo "twiping: can't read ${CONFIG_FILE}" 1>&2
+        exit 1
+    fi
+else
+    # Parse config file
+    . "${CONFIG_FILE}"
 fi
-
-# Parse config file
-. "${CONFIG_FILE}"
 
 # Override some config with command line flags
 if [ -n "${OVERRIDE_FROM_NUMBER}" ]; then
