Rename sendsms(1) -> twimsg(1) to avoid conflict with gnokii-smsd.

diff --git a/trunk/twimsg.in b/trunk/twimsg.in
--- a/trunk/twimsg.in
+++ b/trunk/twimsg.in
@@ -18,7 +18,7 @@ SMSLEN="@bindir@/smslen"
 # Usage message
 usage()
 {
-    echo "Usage: sendsms [-c config.txt] [-e encoding] [-F from-number] [-f file] number" 1>&2
+    echo "Usage: twimsg [-c config.txt] [-e encoding] [-F from-number] [-f file] number" 1>&2
     echo "Options:" 1>&2
     echo "    -c    Specify config file (default \"${DEFAULT_CONFIG_FILE}\")" 1>&2
     echo "    -e    Specify input encoding (default \"${DEFAULT_ENCODING}\")" 1>&2
@@ -86,7 +86,7 @@ esac
 
 # See if config file is readable
 if ! test -r "${CONFIG_FILE}"; then
-    echo "sendsms: can't read ${CONFIG_FILE}" 1>&2
+    echo "twimsg: can't read ${CONFIG_FILE}" 1>&2
     exit 1
 fi
 
@@ -99,19 +99,19 @@ TO_NUMBER=`normalize "${TO_NUMBER}"`
 
 # Sanity check stuff
 if ! [[ "${FROM_NUMBER}" =~ ^\+1[2-9][0-9]{2}[2-9][0-9]{2}[0-9]{4}$ ]]; then
-    echo "sendsms: invalid source phone number \`${FROM_NUMBER}'" 1>&2
+    echo "twimsg: invalid source phone number \`${FROM_NUMBER}'" 1>&2
     exit 1
 fi
 if ! [[ "${TO_NUMBER}" =~ ^\+1[2-9][0-9]{2}[2-9][0-9]{2}[0-9]{4}$ ]]; then
-    echo "sendsms: invalid destination phone number \`${TO_NUMBER}'" 1>&2
+    echo "twimsg: invalid destination phone number \`${TO_NUMBER}'" 1>&2
     exit 1
 fi
 if ! [[ "${ACCOUNT_SID}" =~ ^AC[0-9a-f]{32}$ ]]; then
-    echo "sendsms: invalid account SID \`${ACCOUNT_SID}'" 1>&2
+    echo "twimsg: invalid account SID \`${ACCOUNT_SID}'" 1>&2
     exit 1
 fi
 if ! [[ "${AUTH_TOKEN}" =~ ^[0-9a-f]{32}$ ]]; then
-    echo "sendsms: invalid authentication token" 1>&2
+    echo "twimsg: invalid authentication token" 1>&2
     exit 1
 fi
 
@@ -119,15 +119,15 @@ fi
 URL="`echo ${BASE_URL} | sed 's|/$||g'`""`eval echo ${ACCOUNTS_PATH}`"
 
 # Create temporary files for message response and error
-RESPONSE_FILE=`mktemp -q /tmp/sendsms.XXXXXX`
+RESPONSE_FILE=`mktemp -q /tmp/twimsg.XXXXXX`
 if [ $? -ne 0 ]; then
-    echo "sendsms: can't create temporary file" 1>&2
+    echo "twimsg: can't create temporary file" 1>&2
     exit 1
 fi
-ERROR_FILE=`mktemp -q /tmp/sendsms.XXXXXX`
+ERROR_FILE=`mktemp -q /tmp/twimsg.XXXXXX`
 if [ $? -ne 0 ]; then
     rm -f ${RESPONSE_FILE}
-    echo "sendsms: can't create temporary file" 1>&2
+    echo "twimsg: can't create temporary file" 1>&2
     exit 1
 fi
 trap "rm -f ${RESPONSE_FILE} ${ERROR_FILE}" 0 2 3 5 10 13 15
@@ -146,21 +146,21 @@ cat "${INPUT_FILE}" \
 # Check result
 CURL_RESULT="$?"
 if [ "${CURL_RESULT}" -ne 0 ]; then
-    echo "sendsms: error sending request (curl returned ${CURL_RESULT})" 1>&2
+    echo "twimsg: error sending request (curl returned ${CURL_RESULT})" 1>&2
     exit 1
 fi
 
 # Apply XSLT to returned XML to get error message
 "${XSLTPROC}" "${RESULT_XSL}" "${RESPONSE_FILE}" > "${ERROR_FILE}" 2>&1
 if [ $? -ne 0 ]; then
-    echo -n "sendsms: error parsing result:" 1>&2
+    echo -n "twimsg: error parsing result:" 1>&2
     cat "${ERROR_FILE}" 1>&2
     exit 1
 fi
 
 # Was there an error returned?
 if [ -s "${ERROR_FILE}" ]; then
-    echo -n "sendsms: " 1>&2
+    echo -n "twimsg: " 1>&2
     cat "${ERROR_FILE}" 1>&2
     exit 1
 fi
